data:
    name: my_dataset
    preprocessing:
        resize: 512
        side: long
        square_pad: True
    train_split: train_scenes_clean.txt
    train_num_per_scene: 142
    val_split: valid_scenes_clean.txt
    val_pairs: valid_pairs.txt
    min_overlap: 0.1
    max_overlap: 0.7
    num_overlap_bins: 3
    read_depth: false
    read_image: true
    batch_size: 4
    num_workers: 14
    augmentations:  # Nouvelle section pour les augmentations
        random_rotation_90: true
        horizontal_flip: true
        vertical_flip: true
        random_translation: true
        max_translation: 50
        random_zoom: true
        zoom_range: [0.8, 1.2]
model:
    name: two_view_pipeline
    extractor:
        name: gluefactory_nonfree.superpoint
        max_num_keypoints: 1024
        force_num_keypoints: true
        detection_threshold: 0.003
        nms_radius: 4      
        trainable: True
        randomize_keypoints_training: true
    matcher:
        name: matchers.lightglue
        filter_threshold: 0.0
        flash: false
        checkpointed: true
        n_layers: 6
        num_heads: 4
        width: 128
        loss:
            nll_balancing: 0.7
            gamma_f: 2.0
    ground_truth:
        name: matchers.depth_matcher
        th_positive: 3
        th_negative: 5
        th_epi: 5
    allow_no_extract: True
train:
    seed: 0
    epochs: 36
    log_every_iter: 100
    eval_every_iter: 1000
    lr: 1e-5
    lr_schedule:
        start: 30
        type: exp
        on_epoch: true
        exp_div_10: 10
    dataset_callback_fn: sample_new_items
    plot: [5, 'gluefactory.visualization.visualize_batch.make_match_figures']




